name: cached_network_svg_image
description: A Flutter package for caching SVG images.
version: 1.2.0
homepage: https://github.com/Abdelazeem777/cached_network_svg_image

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.1'

dependencies:
  cross_file: ^0.3.5+1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
